sanity check at the end
This means that if something did go wrong and we didn't end up with
effectively what we started with but stripped-out, there's an
opportunity to either abort or re-commit those missing changes.

diff --git a/git-nbrstrip/git-nbrstrip b/git-nbrstrip/git-nbrstrip
--- a/git-nbrstrip/git-nbrstrip
+++ b/git-nbrstrip/git-nbrstrip
@@ -127,3 +127,15 @@ git log --topo-order --reverse --pretty=%H "$RANGE" | while read SHA; do
     git commit -a -C"$SHA" > /dev/null
 done
 
+# At this point, we're finished. We can now as a sanity check verify
+# that we have all the content we started with, and flag a warning if
+# there is any missing content.
+
+reset_working_tree "$END"
+stripnbs
+if ! [ -z "$(git status --untracked-files=no --porcelain)" ]; then
+    echo "Error: modified files are still present in the repository. This should not happen. Consider filing a bug."
+    echo "You can either choose to continue from this point (by commiting the modified files), or revert back to where you started by running:"
+    echo
+    echo "git reset --hard $END"
+fi
